name: codeflink
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  camera: ^0.10.5+9
  image_picker: ^1.0.7
  intl: ^0.17.0
  geolocator: ^10.1.0
  order_tracker: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  geolocator: ^10.1.1
  geocoding: ^3.0.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/Assets/Temple/Colourful-temples.webp
    - lib/Assets/Temple/madurai-meenakshi-amman-temple.webp
    - lib/Assets/Temple/tourists-at-meenakshi-amman-temple-in-madurai-india.webp
    - lib/Assets/Icon/LOGO.png
    - lib/Assets/HomePageImages/jobcard.jpg
    - lib/Assets/HomePageImages/pendingjobcard.jpg
    - lib/Assets/JobCard/ExistingJob.png
    - lib/Assets/JobCard/New_job.png
    - lib/Assets/JobCard/pendingjob.png
    - lib/Assets/banners/banner1.webp
    - lib/Assets/banners/banner2.webp
    - lib/Assets/banners/banner3.webp



